# ===============================
# CONFIGURACION DEL SERVIDOR
# ===============================
# Railway asigna un puerto aleatorio en producción mediante la variable PORT.
# Si no existe (en tu PC), correrá en el puerto 8080 habitual.
server.port=${PORT:8080}

# ===============================
# CONFIGURACION DE BASE DE DATOS HÍBRIDA (Local: MySQL | Nube: Postgres)
# ===============================
# Si existe DATABASE_URL usa Postgres en Railway. Si no, usa tu MySQL local.
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/techstore_db?useSSL=false&serverTimezone=UTC}

# Configura el driver dinámicamente según la base de datos que se esté usando
spring.datasource.driver-class-name=${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}

# Variables de usuario y contraseña (compatibles con lo que inyecta Railway)
spring.datasource.username=${PGUSER:root}
spring.datasource.password=${PGPASSWORD:1234}

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Dialecto dinámico: usa el de PostgreSQL en la nube o el de MySQL en tu localhost
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}