# ==========================================================================
# CONFIGURACION DEL SERVIDOR
# ==========================================================================
server.port=${PORT:8080}

# ==========================================================================
# CONFIGURACION DE BASE DE DATOS HIBRIDA (LOCAL: MYSQL | NUBE: POSTGRESQL)
# ==========================================================================

# 1. URL de Conexion: Si Railway da la variable usa Postgres, si no, usa tu MySQL local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/techstore_db?useSSL=false&serverTimezone=UTC}

# 2. Driver dinamico: En local usa MySQL, en Railway usa el de PostgreSQL
spring.datasource.driver-class-name=${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}

# 3. Credenciales: Si estas en Railway usa sus variables, si estas en local usa tu root / 1234
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:1234}}

# ==========================================================================
# CONFIGURACION DE JPA / HIBERNATE DINAMICO
# ==========================================================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# 4. Dialecto dinamico: Por defecto usa MySQL, en la nube inyectaremos Postgres
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}