# ===============================
# CONFIGURACION DEL SERVIDOR
# ===============================
server.port=${PORT:8080}

# ===============================
# CONFIGURACION DE BASE DE DATOS HÍBRIDA
# ===============================
# Aquí le decimos que use la URL formateada que le daremos a Railway,
# y si no existe (en tu PC), usará directamente tu MySQL local.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/techstore_db?useSSL=false&serverTimezone=UTC}

# Configura el driver dinámicamente según el entorno
spring.datasource.driver-class-name=${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}

# Credenciales dinámicas (si no existen en tu PC, usa root y 1234)
spring.datasource.username=${PGUSER:root}
spring.datasource.password=${PGPASSWORD:1234}

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}